#pragma once

#define TAP_CODE_DELAY 5
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 1
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define EE_HANDS
#define SPLIT_HAND_MATRIX
#define COMBO_TERM 50
